# Generated by Django 4.1.7 on 2023-03-06 20:50

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('lang', models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru'), ('en', 'En')], default='uz', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('text', 'Text')], default='photo', max_length=5)),
                ('title', models.CharField(blank=True, max_length=55)),
                ('body', django_quill.fields.QuillField()),
                ('media', models.FileField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Short name of your Ad', max_length=55, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('repeat', models.BooleanField(default=True)),
                ('task_id', models.PositiveIntegerField()),
                ('clocked', models.ForeignKey(blank=True, help_text='Schedule time to send ad to users.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.clockedschedule')),
                ('post', models.ForeignKey(help_text='Slect which post do you want to send to users.', on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('send_to', models.ManyToManyField(to='backend.botuser')),
            ],
        ),
    ]
