# Generated by Django 4.1.7 on 2023-03-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='task_id',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
    ]
