# Generated by Django 4.1.7 on 2023-03-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_ad_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='repeat',
        ),
    ]
