# Generated by Django 4.1.7 on 2023-03-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_reklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_post', to='backend.post')),
                ('send_to', models.ManyToManyField(to='backend.botuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Reklama',
        ),
    ]
