# Generated by Django 4.1.7 on 2023-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_ad_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='task_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
