# Generated by Django 4.1.7 on 2023-03-05 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_ad_delete_reklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='send_time',
        ),
        migrations.AddField(
            model_name='ad',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 'Monday'), max_length=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='time',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
