# Generated by Django 4.1.7 on 2023-03-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_ad_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
