# Generated by Django 4.1.7 on 2023-03-05 10:32

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_ad_send_time_ad_days_ad_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=9, verbose_name='Weekdays'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
