# Generated by Django 4.1.7 on 2023-03-05 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_ad_days_alter_ad_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='time',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
