# Generated by Django 4.1.7 on 2023-03-05 10:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_ad_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, verbose_name='Weekdays'),
        ),
    ]
