# Generated by Django 4.1.7 on 2023-03-05 10:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_ad_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255, verbose_name='Weekdays'),
        ),
    ]
