# Generated by Django 4.1.7 on 2023-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_ad_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
    ]
