# Generated by Django 4.1.7 on 2023-03-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('backend', '0009_alter_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='clocked',
            field=models.ForeignKey(blank=True, help_text='Select time for sending AD.If you will not set time, AD will be automatically sent after 10 seconds.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.clockedschedule'),
        ),
    ]
