# Generated by Django 4.1.7 on 2023-03-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_ad_clocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('smile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.smile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='smiles',
            field=models.ManyToManyField(to='backend.smile'),
        ),
    ]
